module.exports = {
    test: require("./_test"),
    getMatchHistory: require("./_getMatchHistory"),
    getTeamFlag: require("./_getTeamFlag"),
    getIndividualHistory: require("./_getIndividualHistory"),
    getTeams: require("./_getTeams"),
    getAwayTeams: require("./_getAwayTeams"),
    getHomeTeams: require("./_getHomeTeams"),
    getLocations: require("./_getLocations"),
    getTournaments: require("./_getTournaments"),
    getAllFlags: require("./_getAllFlags"),
    getVSWinCount: require("./_getVSWinCount"),
    getVSGameCount: require("./_getVSGameCount"),
    getWinCount: require("./_getWinCount"),
    getTotalGamesPlayed: require("./_getTotalGamesPlayed"),
};
